import { Scenario } from '../types';

export const CLINICAL_SCENARIOS: Scenario[] = [
  {
    id: 'sc_aortic_stenosis',
    title: 'Estenosis Aórtica Severa',
    description: 'Paciente masculino mayor que refiere síncope recurrente al subir escaleras.',
    patientName: 'Ramón de los Santos',
    age: 72,
    gender: 'M',
    complaint: 'Síncope de esfuerzo y fatiga de inicio insidioso.',
    vitalSigns: {
      hr: 82,
      rr: 16,
      bp: '110/90',
      spo2: 96,
    },
    activeHotspotId: 'aortico',
    soundModeOverride: 'pathological',
    notes: 'Auscultar foco aórtico. El pulso del paciente es parvus et tardus (débil y retrasado).',
  },
  {
    id: 'sc_asthma_crisis',
    title: 'Crisis Asmática Aguda',
    description: 'Joven con antecedentes de atopía acude con disnea silbante y tos seca.',
    patientName: 'Carla Mejía',
    age: 17,
    gender: 'F',
    complaint: 'Falta de aire súbita tras exposición a alérgenos.',
    vitalSigns: {
      hr: 104,
      rr: 24,
      bp: '120/80',
      spo2: 92,
    },
    activeHotspotId: 'pulmon_ant_sup_der',
    soundModeOverride: 'pathological',
    notes: 'Auscultar campos superiores anteriores. Se perciben ruidos musicales espiratorios.',
  },
  {
    id: 'sc_heart_failure',
    title: 'Insuficiencia Cardíaca Congestiva (ICC)',
    description: 'Paciente con disnea de esfuerzo progresiva que progresa a ortopnea.',
    patientName: 'Héctor Jiménez',
    age: 68,
    gender: 'M',
    complaint: 'Edema de miembros inferiores y fatiga de dos semanas de evolución.',
    vitalSigns: {
      hr: 90,
      rr: 20,
      bp: '140/90',
      spo2: 93,
    },
    activeHotspotId: 'pulmon_ant_inf_izq',
    soundModeOverride: 'pathological',
    notes: 'Auscultar bases pulmonares inferiores. Se perciben estertores finos bilaterales en velcro.',
  },
  {
    id: 'sc_aortic_insufficiency',
    title: 'Insuficiencia Aórtica Aguda',
    description: 'Paciente acude por disnea progresiva de esfuerzo, fatiga y palpitaciones intensas.',
    patientName: 'Eduardo Gómez',
    age: 45,
    gender: 'M',
    complaint: 'Palpitaciones precordiales y dificultad para respirar de inicio subagudo.',
    vitalSigns: {
      hr: 88,
      rr: 18,
      bp: '150/50',
      spo2: 95,
    },
    activeHotspotId: 'erb',
    soundModeOverride: 'pathological',
    notes: 'Auscultar foco accesorio aórtico (Botkin-Erb). Se percibe un soplo diastólico aspirativo decreciente.',
  },
];
